FROM registry.fedoraproject.org/fedora-toolbox:40
EXPOSE 8000
# Add compile any python tools
RUN dnf install -y g++ gcc make pip python3.11 python3-devel python3-GitPython

# Create /instructlab build folder
# Get the InstructLab Github release
# cd into the directory to build from source
RUN mkdir /instructlab
WORKDIR /instructlab

# BUILD
RUN python3 -m venv --upgrade-deps venv
RUN source venv/bin/activate
# RUN pip cache remove llama_cpp_python
RUN pip install git+https://github.com/instructlab/instructlab.git@stable --extra-index-url=https://download.pytorch.org/whl/cpu

# Set up ilab and publish
RUN git clone --recurse-submodules https://github.com/instructlab/taxonomy.git
# Future release, add ability to add your own taxonomy for training
# VOLUME [ "/taxonomy" ]
RUN  yes '' | /usr/local/bin/ilab init --taxonomy-path /instructlab/taxonomy
# Future release, if custom taxonomy is used, train it.
RUN /usr/local/bin/ilab download
RUN /usr/local/bin/ilab serve &

# Future release, add healthcheck
# HEALTHCHECK

ENTRYPOINT ["/usr/local/bin/ilab", "chat"]
